### ISSUE TITLE
Missing references and other issues since last update

### ISSUE THREAD

**Issue by MoritzKrohn** [jackreimers/injact#2] opened 2024-03-06 12:15 UTC
Hi Jack,

I appreciate your implementing dependency injection for Godot 4. Thank you!

Now, I see you restructured some things, very recently. Unfortunately, I have issues with those updates that were not present previously. For one, in many files the using statement for System.Collections.Generic is missing. That's easy to solve, of course, but I have no idea where to get ISourceGenerator, GeneratorAttribute, Generator, GeneratorInitializationContext and GeneratorExecutionContext in ProxyGenerator.cs from. 

Also, Godot shows me a lot of warnings saying "The annotation for nullable reference types should only be used in code within a '#nullable' annotations context." (for example in ObjectBindingStatement.cs:11,18)

And there are solution files (*.sln) present everywhere. Is this intentional? Perhaps in them even lies the solution to all the missing symbols/using-statements, somehow? 

I'm not sure as I'm not used to solution files in Git repositories. 
Perhaps all these things are intentional and you could clarify how to correctly use the new state of the repository?

Best regards

**Comment by jackreimers** [comment] 2024-03-06 13:03
Hi Moritz,

Thanks for raising an issue!

The issues with missing references to ISourceGenerator, GeneratorAttribute, Generator, GeneratorInitializationContext and GeneratorExecutionContext in ProxyGenerator.cs are caused from a missing reference to some code I removed that was not being used. 

I've pushed a fix for this, I think it may be the cause for the majority of your issues.
If you still have errors after you pull the latest changes please let me know and I can investigate further.

There is only one solution at the root level and then code is split into projects (*.csproj) to separate code with different roles (for example keeping tests separate from other code).

I will be working on publishing a nuget package shortly which should make the installation much more simple.

Thanks!

**Comment by jackreimers** [comment] 2024-03-06 13:31
@MoritzKrohn 

I've investigated the issue and the instructions in the readme are incorrect, apologies for that!
Here are the below steps you need to follow:

1. Clone the repo to a file **outside** your Godot project files.
2. Open your Godot solution (.sln file) in Visual Studio/your editor.
3. Add a reference to the Injact.Core and Injact.Godot projects to your solution.
4. Add a reference to Injact.Godot to your Godot **project** (csproj file)

After that everything should be working as expected.
Let me know how you go :)

**Comment by MoritzKrohn** [comment] 2024-03-07 08:41
Now, that worked great, thank you :) ! No more errors or warnings!
Cloning the repository and then referencing the project files also "feels" better compared to downloading the source and copy-pasting it into an "addons"-folder inside my Godot projects. Now I see what you were up to with committing those files into the repository!

Thanks a lot! Also for building and maintaining such a beautiful IoC implementation in the first place!

**Comment by jackreimers** [comment] 2024-03-07 09:11
Great, I'm glad that worked for you!

Thanks for your kind words :)

**Closed as completed by jackreimers** 2024-03-07 09:11 UTC
